#!/usr/bin/env python3
"""Convert protocol/vectors/v1/*.json into vectors_v1.h for the host gtest suite.

Usage: gen_vectors_header.py [VECTORS_DIR] [OUT_HEADER]
Defaults resolve relative to this script: ../../../protocol/vectors/v1 and ./vectors_v1.h.
The generated header is committed so the firmware repo tests stand alone; re-run
after regenerating the vectors.
"""

import json
import os
import sys


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    vec_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.normpath(
        os.path.join(here, "..", "..", "..", "protocol", "vectors", "v1"))
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, "vectors_v1.h")

    frames = []
    bulk = None
    for fn in sorted(os.listdir(vec_dir)):
        if not fn.endswith(".json"):
            continue
        with open(os.path.join(vec_dir, fn), encoding="utf-8") as f:
            v = json.load(f)
        if "write_hex" in v:
            bulk = v
        else:
            frames.append(v)

    out = []
    out.append("// Generated by test/companion_proto/gen_vectors_header.py from protocol/vectors/v1/*.json.")
    out.append("// Do not edit by hand; re-run the script.")
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstddef>")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace vectors_v1 {")
    out.append("")
    out.append("struct Vector {")
    out.append("  const char* name;")
    out.append("  uint8_t type;")
    out.append("  uint16_t seq;")
    out.append("  const char* frame_hex;")
    out.append("  const char* payload_hex;")
    out.append("  uint16_t mtu;  // 0 when the vector carries no segments")
    out.append("  const char* const* segments_hex;")
    out.append("  size_t segments_count;")
    out.append("};")
    out.append("")
    for v in frames:
        segs = v.get("segments_hex")
        if segs:
            out.append(f"static const char* const kSegments_{v['name']}[] = {{")
            for s in segs:
                out.append(f"    {c_str(s)},")
            out.append("};")
    out.append("")
    out.append("static const Vector kVectors[] = {")
    for v in frames:
        segs = v.get("segments_hex")
        seg_ref = f"kSegments_{v['name']}" if segs else "nullptr"
        out.append("    {" + ", ".join([
            c_str(v["name"]), str(v["type"]), str(v["seq"]), c_str(v["frame_hex"]),
            c_str(v["payload_hex"]), str(v.get("mtu", 0)), seg_ref, str(len(segs) if segs else 0),
        ]) + "},")
    out.append("};")
    out.append(f"static const size_t kVectorCount = {len(frames)};")
    out.append("")
    out.append("struct BulkChunkVector {")
    out.append("  const char* name;")
    out.append("  uint16_t chunk_index;")
    out.append("  const char* data_hex;")
    out.append("  const char* write_hex;")
    out.append("};")
    if bulk:
        out.append("static const BulkChunkVector kBulkChunk = {" + ", ".join([
            c_str(bulk["name"]), str(bulk["chunkIndex"]), c_str(bulk["data_hex"]), c_str(bulk["write_hex"])]) + "};")
    out.append("")
    out.append("}  // namespace vectors_v1")
    out.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {out_path}: {len(frames)} frame vectors" + (", 1 bulk chunk" if bulk else ""))


if __name__ == "__main__":
    main()
